### ISSUE TITLE
A2aAgent: agent_card serialization crashes with AttributeError: 'AgentCard' object has no attribute 'DESCRIPTOR' (regression in 1.150.0)

### ISSUE THREAD

**Issue by eliasecchig** [googleapis/python-aiplatform#6811]
## Summary

Since `google-cloud-aiplatform==1.150.0`, building an `AgentEngine` from an `A2aAgent` whose `agent_card` is an `a2a.types.AgentCard` crashes during class-methods spec generation. This is a regression — `1.149.0` works fine.

The Vertex SDK is internally inconsistent: `vertexai.preview.reasoning_engines.A2aAgent` accepts and stores a Pydantic `a2a.types.AgentCard` (the type returned by ADK's `AgentCardBuilder` and the canonical type in `a2a-sdk`), but `_agent_engines_utils._generate_class_methods_spec_or_raise` then tries to serialize it with `google.protobuf.json_format.MessageToJson`, which requires a protobuf `Message`.

## Environment

- `google-cloud-aiplatform`: **1.150.0 through 1.153.1** (latest) — all broken
- `google-cloud-aiplatform`: **1.149.0** and earlier — works
- `google-adk`: 1.33.0
- `a2a-sdk`: 0.3.26
- Python: 3.12

## Regression

In `vertexai/_genai/_agent_engines_utils.py` around line 635:

```python
# 1.149.0 (works) — passes the card through as-is
if hasattr(agent, "agent_card"):
    class_method[_A2A_AGENT_CARD] = getattr(agent, "agent_card")

# 1.150.0+ (broken) — assumes protobuf
if hasattr(agent, "agent_card"):
    class_method[_A2A_AGENT_CARD] = json_format.MessageToJson(
        getattr(agent, "agent_card")
    )
```

The change to wrap with `MessageToJson` assumes the stored `agent_card` is a protobuf `Message`. But the `A2aAgent` constructor in the same SDK accepts a Pydantic `a2a.types.AgentCard` (from `a2a-sdk`), which is how ADK supplies it.

## Reproduction

```python
import asyncio
from a2a.types import AgentCapabilities, AgentCard, TransportProtocol
from google.adk.a2a.executor.a2a_agent_executor import A2aAgentExecutor
from google.adk.a2a.utils.agent_card_builder import AgentCardBuilder
from google.adk.agents import Agent
from google.adk.apps import App
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from vertexai.preview.reasoning_engines import A2aAgent
from vertexai._genai import _agent_engines_utils

root_agent = Agent(name="hello", model="gemini-2.0-flash", instruction="Say hi.")
app = App(name="hello-app", root_agent=root_agent)

async def make_card():
    builder = AgentCardBuilder(
        agent=root_agent,
        capabilities=AgentCapabilities(streaming=False),
        rpc_url="http://localhost:9999/",
    )
    card = await builder.build()
    card.preferred_transport = TransportProtocol.http_json
    return card

card = asyncio.run(make_card())

agent = A2aAgent(
    agent_executor_builder=lambda: A2aAgentExecutor(
        runner=Runner(app=app, session_service=InMemorySessionService(), artifact_service=None)
    ),
    agent_card=card,
)

ops = _agent_engines_utils._get_registered_operations(agent=agent)
_agent_engines_utils._generate_class_methods_spec_or_raise(agent=agent, operations=ops)
```

## Stack trace

```
File ".../vertexai/_genai/_agent_engines_utils.py", line 636,
  in _generate_class_methods_spec_or_raise
    class_method[_A2A_AGENT_CARD] = json_format.MessageToJson(
File ".../google/protobuf/json_format.py", line 212, in _MessageToJsonObject
    message_descriptor = message.DESCRIPTOR
File ".../pydantic/main.py", line 1026, in __getattr__
    raise AttributeError(...)
AttributeError: 'AgentCard' object has no attribute 'DESCRIPTOR'
```

## Suggested fix

Branch on the card type, since both Pydantic (`a2a-sdk`) and protobuf cards are reachable via this code path:

```python
if hasattr(agent, "agent_card"):
    card = getattr(agent, "agent_card")
    if hasattr(card, "model_dump_json"):       # Pydantic (a2a-sdk)
        class_method[_A2A_AGENT_CARD] = card.model_dump_json()
    elif hasattr(card, "DESCRIPTOR"):          # protobuf Message
        class_method[_A2A_AGENT_CARD] = json_format.MessageToJson(card)
    else:
        class_method[_A2A_AGENT_CARD] = card   # fall back to 1.149.0 behavior
```

## Workaround

Pin `google-cloud-aiplatform<1.150` until this is resolved.

**Comment by eliasecchig** [comment]
Tracked down the regression to commit [`762d20c`](https://github.com/googleapis/python-aiplatform/commit/762d20c) (May 5, 2026) — "feat: update sdk to support python-a2a sdk 1.0 via a new GA A2a framework template", shipped in `1.150.0`.

That commit didn't just add a wrong assumption; it **replaced** a Pydantic-aware serializer with the protobuf one:

```python
# Before (worked with a2a-sdk 0.3.x Pydantic AgentCard)
class_method[_A2A_AGENT_CARD] = getattr(agent, "agent_card").model_dump_json()

# After (assumes protobuf — breaks Pydantic cards)
class_method[_A2A_AGENT_CARD] = json_format.MessageToJson(
    getattr(agent, "agent_card")
)
```

The same swap was applied to the equivalent function in `vertexai/agent_engines/_agent_engines.py`.

Looks like the intent was to support the upcoming python-a2a SDK 1.0 GA (which uses protobuf cards), but it dropped support for `a2a-sdk 0.3.x` Pydantic cards — which is what `google-adk`'s `AgentCardBuilder` returns today. The fix is presumably to keep both branches (Pydantic via `.model_dump_json()`, protobuf via `MessageToJson`).

**Comment by Abeansits** [comment]
can we get some attention to this one plz @matthew29tang 🙏

**Comment by matthew29tang** [comment]
The fix was just submitted yesterday here: https://github.com/googleapis/python-aiplatform/commit/4c0c36807a5ac98c79cd4bf158654534cc625d00

It'll be included in next Tuesday's release
