### ISSUE TITLE
AttributeError: 'ClientOptions' object has no attribute 'api_audience'

### ISSUE THREAD

**Issue by Ark-kun** [googleapis/python-aiplatform#1554]
The aiplatform package code is currently incompatible with `google-cloud-core==2.2.3`

The issue was introduced by https://github.com/googleapis/python-aiplatform/pull/1454 and https://github.com/googleapis/googleapis/commit/23f1a157189581734c7a77cddfeb7c5bc1e440ae

#### Environment details

  - `google-cloud-aiplatform` version: 1.15.1

#### Stack trace
```
/opt/conda/lib/python3.7/site-packages/google/cloud/aiplatform/utils/__init__.py in __getattr__(self, name)
    357                 credentials=self._credentials,
    358                 client_options=self._client_options,
--> 359                 client_info=self._client_info,
    360             )
    361             return getattr(temporary_client, name)

/opt/conda/lib/python3.7/site-packages/google/cloud/aiplatform_v1/services/pipeline_service/client.py in __init__(self, credentials, transport, client_options, client_info)
    626                 client_info=client_info,
    627                 always_use_jwt_access=True,
--> 628                 api_audience=client_options.api_audience,
    629             )
    630 

AttributeError: 'ClientOptions' object has no attribute 'api_audience'
```

See https://github.com/googleapis/python-cloud-core/issues/208

**Comment by temurchichua** [comment]
Do I have to stick with `google-api-core >= 1.31.6` or is there any other solution for this one?
